# Would be production compose file
services:
  pong:
    container_name: pong
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    working_dir: /pong
    volumes:
      - .:/pong
    command: tail -f /dev/null
    ports:
      - "3000:3000"
      - "4000:4000"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
    